nome = input('Informe seu nome: ')
objetivo = input('Informe um dos seus objetivos: ')
obstaculo_objetivo = input('Informe algo que esteja sendo um obstáculo para seu objetivo: ')
frase = input('Me fala uma frase motivacional que você usa: ')
print(f'Olá, sou a Hevilin. É um prazer {nome}, sempre vão existir obstáculos como {obstaculo_objetivo}, mas nunca desista do seu objetivo de {objetivo}. Como alguém sempre diz: {frase}.')